# Generated by Django 5.1.7 on 2025-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwrodresetrequest',
            name='token',
            field=models.CharField(default='dkWb7pAmqv8oHkoK0zNWKWdiIQz0iVWM', editable=False, max_length=32, unique=True),
        ),
    ]
