# Generated by Django 5.1.7 on 2025-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwrodresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwrodresetrequest',
            name='token',
            field=models.CharField(default='X8Z0GQ7EYf77ucMMAaPgme6W6zZmdQCN', editable=False, max_length=32, unique=True),
        ),
    ]
