# Generated by Django 5.1.7 on 2025-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwrodresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='emial',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='passwrodresetrequest',
            name='token',
            field=models.CharField(default='Tl0djr0bxLKx3PvVWRcjJDWciNyOA0l0', editable=False, max_length=32, unique=True),
        ),
    ]
